### ISSUE TITLE
HTTP 500 when resource id:3895 is cross-referenced

### ISSUE THREAD

**Issue by crantila** [CANTUS-Project/abbot#96]
It's from a SEARCH request for ``+type:source``.

The `journald` log:

    Jan 10 21:43:13 abbott.adjectivenoun.ca abbot[27212]: Abbot Server 0.4.8 for Cantus API 0.2.3 is starting up!
    Jan 10 21:43:15 abbott.adjectivenoun.ca abbot[27212]: 200 OPTIONS /browse/ (::ffff:10.0.1.1) 1.44ms
    Jan 10 21:43:15 abbott.adjectivenoun.ca abbot[27212]: util.parse_query() begins "type:* +type:source"
    Jan 10 21:43:15 abbott.adjectivenoun.ca abbot[27212]: util.search_solr() submits "type:*  +type:source "
    Jan 10 21:43:15 abbott.adjectivenoun.ca abbot[27212]: Starting request to 'http://localhost:8983/solr/collection1/select/?rows=10&q=type%3A%2A++%2Btype%3Asource+&df=default_search&wt=json' (GET) with body ''...
    Jan 10 21:43:15 abbott.adjectivenoun.ca abbot[27212]: Finished 'http://localhost:8983/solr/collection1/select/?rows=10&q=type%3A%2A++%2Btype%3Asource+&df=default_search&wt=json' (GET) with body '' in 0.008 seconds.
    Jan 10 21:43:15 abbott.adjectivenoun.ca abbot[27212]: Found '484' search results.
    Jan 10 21:43:15 abbott.adjectivenoun.ca abbot[27212]: util.search_solr() submits "+type:notation +id:3895"
    Jan 10 21:43:15 abbott.adjectivenoun.ca abbot[27212]: Starting request to 'http://localhost:8983/solr/collection1/select/?wt=json&q=%2Btype%3Anotation+%2Bid%3A3895&df=default_search' (GET) with body ''...
    Jan 10 21:43:15 abbott.adjectivenoun.ca abbot[27212]: Finished 'http://localhost:8983/solr/collection1/select/?wt=json&q=%2Btype%3Anotation+%2Bid%3A3895&df=default_search' (GET) with body '' in 0.004 seconds.
    Jan 10 21:43:15 abbott.adjectivenoun.ca abbot[27212]: Found '1' search results.
    Jan 10 21:43:15 abbott.adjectivenoun.ca abbot[27212]: 500 SEARCH /browse/ (::ffff:10.0.1.1) 20.87ms

**Comment by crantila** [comment]
Also, it "five hundreded" when I gave ``+differentia:`` as the query string for a SEARCH request on the ``/browse/`` URL.

**Comment by crantila** [comment]
Here's the actual traceback.

    Traceback (most recent call last):
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/abbot/simple_handler.py", line 260, in make_resource_url
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/tornado/web.py", line 1330, in reverse_url
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/tornado/web.py", line 1925, in reverse_url
    KeyError: 'view_* not found in named urls'

    Traceback (most recent call last):
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/abbot/util.py", line 372, in decorated
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/tornado/gen.py", line 1008, in run
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/tornado/concurrent.py", line 232, in result
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/tornado/gen.py", line 1014, in run
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/abbot/simple_handler.py", line 811, in search
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/tornado/gen.py", line 1008, in run
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/tornado/concurrent.py", line 232, in result
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/tornado/gen.py", line 1014, in run
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/abbot/simple_handler.py", line 771, in search_handler
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/tornado/gen.py", line 1008, in run
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/tornado/concurrent.py", line 232, in result
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/tornado/gen.py", line 1014, in run
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/abbot/complex_handler.py", line 222, in get_handler
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/tornado/gen.py", line 1008, in run
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/tornado/concurrent.py", line 232, in result
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/tornado/gen.py", line 1017, in run
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/abbot/complex_handler.py", line 155, in look_up_xrefs
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/abbot/simple_handler.py", line 264, in make_resource_url
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/tornado/web.py", line 1330, in reverse_url
      File "/usr/local/abbot-venv/lib64/python3.4/site-packages/tornado/web.py", line 1925, in reverse_url
    KeyError: 'view_* not found in named urls'

**Comment by crantila** [comment]
I found the problem!

In a Source with the "notation_style_id" field, which is cross-referenced to Notation resources, [this call](https://github.com/CANTUS-Project/abbot/blob/06aa1c4ad6bc164293a6ca63f171fc3c6640a3bb/abbot/complex_handler.py#L151) to `singular_resource_to_plural()` fails because there is no resource type "notation_style," but that's what `LOOKUP` says to look up. However, when `singular_resource_to_plural()` fails, it simply returns ``None``.

Therefore the ``plural`` argument to `make_resource_url()` [here](https://github.com/CANTUS-Project/abbot/blob/06aa1c4ad6bc164293a6ca63f171fc3c6640a3bb/abbot/complex_handler.py#L155) is ``None``, which then becomes ``self.type_name_plural`` [in that function](https://github.com/CANTUS-Project/abbot/blob/06aa1c4ad6bc164293a6ca63f171fc3c6640a3bb/abbot/simple_handler.py#L255).

There are two results of this:

1. for `/sources/` URLs, where ``type_name_plural`` is set to ``'sources'``, the Notation cross-reference URLs are incorrect because they contain `/sources/` instead of `/notations/`.
1. for the `/browse/` URL, where ``type_name_plural`` is set to ``'*'``, `reverse_url()` raises an exception because there is, indeed, no URL handler called ``'view_*'``.

So I'm going to do four things to solve this problem:
- [ ] Refactor [this line](https://github.com/CANTUS-Project/abbot/blob/06aa1c4ad6bc164293a6ca63f171fc3c6640a3bb/abbot/complex_handler.py#L151) to use the "type" member, which is the same for every resource type except Notation.
- [ ] Refactor `util.singular_resource_to_plural()` so it raises `KeyError` when the resource isn't found.
- [ ] Add a regression test to ensure xref links to Notation resources are correct.
- [ ] Add a regression test to ensure the `/browse/` URL works
